package org.campagnelab.metar.R.inspect.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.campagnelab.metar.R.gen.behavior.IGenerateToRScript__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import java.io.File;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_962445451564175837(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x39af1051e1175767L, 0x39af1051e1175768L, "id"));
  }
  public static Object propertyMacro_GetPropertyValue_8016431400514006106(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f4488ace3L, 0x6f4015e2c9ecbde8L, "tableName"));
  }
  public static Object propertyMacro_GetPropertyValue_8016431400514009759(final PropertyMacroContext _context) {
    return IGenerateToRScript__BehaviorDescriptor.getResultsDir_id7klrZ4rJNMW.invoke(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getInterfaceConcept(0x837afec3cff045b1L, 0xa2216b811148f87eL, 0x638ffcae8ff6bdd6L, "org.campagnelab.metar.R.gen.structure.IGenerateToRScript"), false, false)) + File.separator + SModelOperations.getModelName(SNodeOperations.getModel(_context.getNode())) + File.separator + "table_" + SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f4488ace3L, 0x6f4015e2c9ecbde8L, "tableName")) + "_" + Integer.toString(SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f4488ace3L, 0x157f2d8812f7de15L, "tableId"))) + ".tsv";
  }
  public static Object propertyMacro_GetPropertyValue_1369498147940464982(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448adddbL, 0x7c7b9355b28afec0L, "nodeId"));
  }
  public static Object propertyMacro_GetPropertyValue_1369498147940466129(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448adddbL, 0x7c7b9355b28afec0L, "nodeId"));
  }
  public static Object propertyMacro_GetPropertyValue_1369498147940466311(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448adddbL, 0x7c7b9355b28afec0L, "nodeId"));
  }
  public static Object propertyMacro_GetPropertyValue_1369498147941731525(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f4627L, "pngPath"));
  }
  public static Object propertyMacro_GetPropertyValue_1369498147941795250(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044bcL, "width")));
  }
  public static Object propertyMacro_GetPropertyValue_1369498147941799268(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044c0L, "height")));
  }
  public static Object propertyMacro_GetPropertyValue_1369498147941732490(final PropertyMacroContext _context) {
    return "plot_" + SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f40f0L, "plotId"));
  }
  public static Object propertyMacro_GetPropertyValue_1369498147941730058(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44b83dc3L, "statementId"));
  }
  public static Object propertyMacro_GetPropertyValue_95082356236489299(final PropertyMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x151cce633e21140L, "errorCatching"));
  }
  public static boolean ifMacro_Condition_1369498147940452069(final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448adddbL, 0x260d91b381fb25b7L, "enabled"));
  }
  public static boolean ifMacro_Condition_1369498147940418690(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448ae41bL, 0x7c7b9355b2755728L, "uponWarning")) != null);
  }
  public static boolean ifMacro_Condition_1369498147940423111(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448ae41bL, 0x7c7b9355b2755734L, "finally")) != null);
  }
  public static SNode sourceNodeQuery_1369498147940438593(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448adddbL, 0x13016f4f448adedaL, "try"));
  }
  public static SNode sourceNodeQuery_1369498147940452709(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448adddbL, 0x13016f4f448adedaL, "try"));
  }
  public static SNode sourceNodeQuery_1369498147940417175(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448ae41bL, 0x7c7b9355b2755725L, "try"));
  }
  public static SNode sourceNodeQuery_1369498147940421657(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448ae41bL, 0x7c7b9355b2755728L, "uponWarning"));
  }
  public static SNode sourceNodeQuery_1369498147940421505(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448ae41bL, 0x7c7b9355b275572dL, "uponError"));
  }
  public static SNode sourceNodeQuery_1369498147940426024(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448ae41bL, 0x7c7b9355b2755734L, "finally"));
  }
}
