package org.campagnelab.metar.sleuth;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.TemplateModuleInterpreted2;
import jetbrains.mps.smodel.language.LanguageRegistry;
import jetbrains.mps.smodel.language.LanguageRuntime;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.module.SModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import org.campagnelab.metar.sleuth.generator.template.main.QueriesGenerated;
import jetbrains.mps.generator.runtime.TemplateModuleBase;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SLanguage;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Arrays;
import jetbrains.mps.generator.runtime.TemplateMappingPriorityRule;
import jetbrains.mps.generator.runtime.TemplateUtil;

public class Generator extends TemplateModuleInterpreted2 {

  public Generator(LanguageRegistry languageRegistry, LanguageRuntime sourceLanguage, jetbrains.mps.smodel.Generator generator) {
    super(languageRegistry, sourceLanguage, generator);
  }

  @NotNull
  @Override
  public SModuleReference getModuleReference() {
    return PersistenceFacade.getInstance().createModuleReference("46ceb6f0-f27b-475f-9bc7-9c906c006ec7(org.campagnelab.metar.sleuth#3554287509434082151)");
  }

  @Override
  protected void fillTemplateModels(TemplateModuleInterpreted2.TemplateModels models) {
    models.templates("r:581a82a3-86cf-48cc-b17a-2b77ca4ac1b4", QueriesGenerated.class);
  }

  @Override
  protected void fillReferencedGenerators(TemplateModuleBase.ReferencedGenerators referencedGenerators) {
    referencedGenerators.employed("5b6b815e-ae64-460e-9ea1-cddb68a0fee9(org.campagnelab.metar.limma#5124039371745995804)");
  }

  @Override
  public Collection<SLanguage> getTargetLanguages() {
    SLanguage[] rv = new SLanguage[2];
    rv[0] = MetaAdapterFactory.getLanguage(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, "org.campagnelab.metar.R");
    rv[1] = MetaAdapterFactory.getLanguage(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, "org.campagnelab.metar.R.inspect");
    return Arrays.asList(rv);
  }

  @Override
  public Collection<TemplateMappingPriorityRule> getPriorities() {
    return TemplateUtil.asCollection(TemplateUtil.createStrictlyTogetherRule(TemplateUtil.createRefExternal("46ceb6f0-f27b-475f-9bc7-9c906c006ec7(org.campagnelab.metar.sleuth#3554287509434082151)", TemplateUtil.createRefLocal()), TemplateUtil.createRefExternal("5b6b815e-ae64-460e-9ea1-cddb68a0fee9(org.campagnelab.metar.limma#5124039371745995804)", TemplateUtil.createRefLocal())));
  }
}
