package org.campagnelab.metar.plots.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.PropertyMacroContext;
import org.campagnelab.metar.tables.behavior.Plot__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.internal.collections.runtime.IterableUtils;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.ISelector;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.campagnelab.metar.plots.behavior.MAPlot__BehaviorDescriptor;
import org.campagnelab.metar.code.generator.helpers.RPath;
import org.campagnelab.instantrefresh.behavior.IAtomic__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.campagnelab.metar.plots.behavior.IdsFrom__BehaviorDescriptor;
import jetbrains.mps.internal.collections.runtime.Sequence;
import org.campagnelab.metar.tables.behavior.Table__BehaviorDescriptor;
import org.campagnelab.metar.tables.behavior.ISaveRVariableInSession__BehaviorDescriptor;
import org.campagnelab.metar.tables.behavior.Statement__BehaviorDescriptor;
import org.campagnelab.metar.code.generator.helpers.NameHelper;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.generator.template.TemplateVarContext;
import org.campagnelab.metar.tables.behavior.ColumnLabel__BehaviorDescriptor;
import java.util.Map;
import jetbrains.mps.generator.impl.query.SourceNodeQuery;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import jetbrains.mps.generator.impl.query.QueryKeyImpl;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.Collection;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.generator.impl.query.IfMacroCondition;
import jetbrains.mps.generator.impl.query.VariableValueQuery;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static Object propertyMacro_GetValue_1_0(final PropertyMacroContext _context) {
    return "plot_" + Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x543d7279f11a839aL, "plot")));
  }
  public static Object propertyMacro_GetValue_1_1(final PropertyMacroContext _context) {
    return ((String) _context.getVariable("var:statsTableName"));
  }
  public static Object propertyMacro_GetValue_1_2(final PropertyMacroContext _context) {
    return IterableUtils.join(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x34ed91dae4daf622L, "geneList")), MetaAdapterFactory.getContainmentLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x39d2cd96c5aecb7bL, 0x39d2cd96c5aef550L, "ids"))).select(new ISelector<SNode, String>() {
      public String select(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x39d2cd96c5aecb7cL, 0x39d2cd96c5aecb7dL, "id"));
      }
    }), "\", \"");
  }
  public static Object propertyMacro_GetValue_1_3(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.getColumnGeneName_id5hNeoO0Owq.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_4(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.fdrColName_id3AJ457wDmra.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_5(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x34ed91dae4ac24d9L, "significanceLevelFDR"));
  }
  public static Object propertyMacro_GetValue_1_6(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.fdrColName_id3AJ457wDmra.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_7(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x34ed91dae4ac24d9L, "significanceLevelFDR"));
  }
  public static Object propertyMacro_GetValue_1_8(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.meanColName_id3AJ457wDpYP.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_9(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x34ed91dae4ac24deL, "minExpression"));
  }
  public static Object propertyMacro_GetValue_1_10(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.getIDColumnName_id5hNeoO2GzH.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_11(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.meanColName_id3AJ457wDpYP.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_12(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.logFCColName_id3AJ457wDny1.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_13(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.getIDColumnName_id5hNeoO2GzH.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_14(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.getIDColumnName_id5hNeoO2GzH.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_15(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.getIDColumnName_id5hNeoO2GzH.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_16(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.getXRangeMin_id4FCgsrOAv7q.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_17(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.getXRangeMax_idLUoY2o4Ef0.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_18(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.getYRangeMin_idLUoY2o4IL8.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_19(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.getYRangeMax_idLUoY2o4ILt.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_20(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.getTitle_idLUoY2o4Y1i.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_21(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x34ed91dae4ac24deL, "minExpression"));
  }
  public static Object propertyMacro_GetValue_1_22(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x34ed91dae4ac24deL, "minExpression"));
  }
  public static Object propertyMacro_GetValue_1_23(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.getIDColumnName_id5hNeoO2GzH.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_24(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.getColumnGeneName_id5hNeoO0Owq.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_25(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.meanColName_id3AJ457wDpYP.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_26(final PropertyMacroContext _context) {
    return (String) MAPlot__BehaviorDescriptor.logFCColName_id3AJ457wDny1.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_27(final PropertyMacroContext _context) {
    return Float.toString((float) MAPlot__BehaviorDescriptor.getGeneNameSize_id5hNeoO9xNB.invoke(_context.getNode()));
  }
  public static Object propertyMacro_GetValue_1_28(final PropertyMacroContext _context) {
    return new RPath(Plot__BehaviorDescriptor.getPath_id6X05ubabEHv.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x543d7279f11a839aL, "plot")))).toString();
  }
  public static Object propertyMacro_GetValue_1_29(final PropertyMacroContext _context) {
    return (String) Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x543d7279f11a839aL, "plot")));
  }
  public static Object propertyMacro_GetValue_1_30(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getWidth_id32mm940cTd2.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x543d7279f11a839aL, "plot")));
  }
  public static Object propertyMacro_GetValue_1_31(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getHeight_id32mm940d1rP.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x543d7279f11a839aL, "plot")));
  }
  public static Object propertyMacro_GetValue_1_32(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x7c5f892f445924a8L, "org.campagnelab.metar.tables.structure.Statement")));
  }
  public static Object propertyMacro_GetValue_2_0(final PropertyMacroContext _context) {
    return "plot_" + Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x13016f4f44936489L, 0x51f1c789d32d78aL, "plot")));
  }
  public static Object propertyMacro_GetValue_2_1(final PropertyMacroContext _context) {
    return (String) IdsFrom__BehaviorDescriptor.name_id1c1rOX4B7u7.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_2_2(final PropertyMacroContext _context) {
    return IterableUtils.join(Sequence.fromIterable(IdsFrom__BehaviorDescriptor.ids_id1c1rOX4Be7z.invoke(_context.getNode())), "\",\"");
  }
  public static Object propertyMacro_GetValue_2_3(final PropertyMacroContext _context) {
    return (String) IdsFrom__BehaviorDescriptor.name_id1c1rOX4B7u7.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_2_4(final PropertyMacroContext _context) {
    return (String) IdsFrom__BehaviorDescriptor.name_id1c1rOX4B7u7.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_2_5(final PropertyMacroContext _context) {
    return new RPath(Plot__BehaviorDescriptor.getPath_id6X05ubabEHv.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x13016f4f44936489L, 0x51f1c789d32d78aL, "plot")))).toString();
  }
  public static Object propertyMacro_GetValue_2_6(final PropertyMacroContext _context) {
    return (String) Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x13016f4f44936489L, 0x51f1c789d32d78aL, "plot")));
  }
  public static Object propertyMacro_GetValue_2_7(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getWidth_id32mm940cTd2.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x13016f4f44936489L, 0x51f1c789d32d78aL, "plot")));
  }
  public static Object propertyMacro_GetValue_2_8(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getHeight_id32mm940d1rP.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x13016f4f44936489L, 0x51f1c789d32d78aL, "plot")));
  }
  public static Object propertyMacro_GetValue_2_9(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x7c5f892f445924a8L, "org.campagnelab.metar.tables.structure.Statement")));
  }
  public static Object propertyMacro_GetValue_4_0(final PropertyMacroContext _context) {
    return IterableUtils.join(Sequence.fromIterable(IdsFrom__BehaviorDescriptor.ids_id1c1rOX4Be7z.invoke(_context.getNode())), "\",\"");
  }
  public static Object propertyMacro_GetValue_6_0(final PropertyMacroContext _context) {
    return _context.createUniqueName("calculateTSNE", SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getInterfaceConcept(0x837afec3cff045b1L, 0xa2216b811148f87eL, 0x638ffcae8ff6bdd6L, "org.campagnelab.metar.R.gen.structure.IGenerateToRScript"), false, false));
  }
  public static Object propertyMacro_GetValue_6_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(Sequence.fromIterable(Table__BehaviorDescriptor.findColumnsWithGroup_id5hNeoNXWkF.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae347d9fL, "statsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")), MetaAdapterFactory.getContainmentLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd605ac5L, 0x39d2cd96c5e85fcbL, "myOwnTable")), "ID")).first(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetValue_6_2(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae368cbcL, "randomSeed")));
  }
  public static Object propertyMacro_GetValue_6_3(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae347f57L, "theta")).toString();
  }
  public static Object propertyMacro_GetValue_6_4(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae347fdbL, "numIterations")));
  }
  public static Object propertyMacro_GetValue_6_5(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x45b42afdc2d8d41eL, "perplexity")).toString();
  }
  public static Object propertyMacro_GetValue_6_6(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae368cbcL, "randomSeed")));
  }
  public static Object propertyMacro_GetValue_6_7(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x6e568be56e983618L, "numberOfClusters")));
  }
  public static Object propertyMacro_GetValue_6_8(final PropertyMacroContext _context) {
    return (String) ISaveRVariableInSession__BehaviorDescriptor.getVariableName_id52J4nYvd$7N.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae347d9fL, "statsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")));
  }
  public static Object propertyMacro_GetValue_6_9(final PropertyMacroContext _context) {
    return "plot_" + Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae347da0L, "plot")));
  }
  public static Object propertyMacro_GetValue_6_10(final PropertyMacroContext _context) {
    return (String) ISaveRVariableInSession__BehaviorDescriptor.getVariableName_id52J4nYvd$7N.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae347d9fL, "statsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")));
  }
  public static Object propertyMacro_GetValue_6_11(final PropertyMacroContext _context) {
    return (String) ISaveRVariableInSession__BehaviorDescriptor.getVariableName_id52J4nYvd$7N.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x21460732b38d1815L, "tsneTable")));
  }
  public static Object propertyMacro_GetValue_6_12(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x21460732b38d1815L, "tsneTable")), MetaAdapterFactory.getProperty(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd605ac5L, 0x39d2cd96c5e52d3dL, "id"));
  }
  public static Object propertyMacro_GetValue_6_13(final PropertyMacroContext _context) {
    return new RPath(Plot__BehaviorDescriptor.getPath_id6X05ubabEHv.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae347da0L, "plot")))).toString();
  }
  public static Object propertyMacro_GetValue_6_14(final PropertyMacroContext _context) {
    return (String) Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae347da0L, "plot")));
  }
  public static Object propertyMacro_GetValue_6_15(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getWidth_id32mm940cTd2.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae347da0L, "plot")));
  }
  public static Object propertyMacro_GetValue_6_16(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getHeight_id32mm940d1rP.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae347da0L, "plot")));
  }
  public static Object propertyMacro_GetValue_6_17(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x7c5f892f445924a8L, "org.campagnelab.metar.tables.structure.Statement")));
  }
  public static Object propertyMacro_GetValue_6_18(final PropertyMacroContext _context) {
    return (String) ISaveRVariableInSession__BehaviorDescriptor.getVariableName_id52J4nYvd$7N.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x21460732b38d1815L, "tsneTable")));
  }
  public static Object propertyMacro_GetValue_6_19(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_6_20(final PropertyMacroContext _context) {
    return (boolean) Statement__BehaviorDescriptor.errorCatchingEnabled_id2od$re20jdz.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_7_0(final PropertyMacroContext _context) {
    return "plot_" + Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0xc2b9f44459b7911L, 0xc2b9f44459b7919L, "plot")));
  }
  public static Object propertyMacro_GetValue_7_1(final PropertyMacroContext _context) {
    return (String) ISaveRVariableInSession__BehaviorDescriptor.getVariableName_id52J4nYvd$7N.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0xc2b9f44459b7911L, 0xc2b9f44459b7918L, "inputTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")));
  }
  public static Object propertyMacro_GetValue_7_2(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0xc2b9f44459b7911L, 0x26f5565b738cca52L, "color")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd83b499L, 0x2f3745fadd83b49aL, "col")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
  }
  public static Object propertyMacro_GetValue_7_3(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0xc2b9f44459b7911L, 0x26f5565b738cca52L, "color")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd83b499L, 0x2f3745fadd83b49aL, "col")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetValue_7_4(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0xc2b9f44459b7911L, 0x26f5565b738cc9a5L, "x")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd83b499L, 0x2f3745fadd83b49aL, "col")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
  }
  public static Object propertyMacro_GetValue_7_5(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0xc2b9f44459b7911L, 0x26f5565b738cca43L, "y")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd83b499L, 0x2f3745fadd83b49aL, "col")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetValue_7_6(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0xc2b9f44459b7911L, 0x26f5565b738cca52L, "color")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd83b499L, 0x2f3745fadd83b49aL, "col")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
  }
  public static Object propertyMacro_GetValue_7_7(final PropertyMacroContext _context) {
    return new RPath(Plot__BehaviorDescriptor.getPath_id6X05ubabEHv.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0xc2b9f44459b7911L, 0xc2b9f44459b7919L, "plot")))).toString();
  }
  public static Object propertyMacro_GetValue_7_8(final PropertyMacroContext _context) {
    return (String) Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0xc2b9f44459b7911L, 0xc2b9f44459b7919L, "plot")));
  }
  public static Object propertyMacro_GetValue_7_9(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getWidth_id32mm940cTd2.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0xc2b9f44459b7911L, 0xc2b9f44459b7919L, "plot")));
  }
  public static Object propertyMacro_GetValue_7_10(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getHeight_id32mm940d1rP.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0xc2b9f44459b7911L, 0xc2b9f44459b7919L, "plot")));
  }
  public static Object propertyMacro_GetValue_7_11(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x7c5f892f445924a8L, "org.campagnelab.metar.tables.structure.Statement")));
  }
  public static Object propertyMacro_GetValue_7_12(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_7_13(final PropertyMacroContext _context) {
    return (boolean) Statement__BehaviorDescriptor.errorCatchingEnabled_id2od$re20jdz.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_8_0(final PropertyMacroContext _context) {
    String start = "";
    String end = "";
    if (SPropertyOperations.getBoolean(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x22adea88774e16beL, 0x22adea88775261a4L, "ids")), MetaAdapterFactory.getProperty(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x22adea8877525e03L, 0x22adea8877ac0ecfL, "toUpperCase"))) {
      start = "toupper(";
      end = ")";
    }
    return start + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x22adea88774e16beL, 0x22adea88775261a4L, "ids")), MetaAdapterFactory.getContainmentLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x22adea8877525e03L, 0x22adea88775261f2L, "column")), MetaAdapterFactory.getReferenceLink(0x7eba6a284cc247b9L, 0xa392284573f2054aL, 0x43b3173822924fd2L, 0x77ebff5909168461L, "futureTable")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "$" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x22adea88774e16beL, 0x22adea88775261a4L, "ids")), MetaAdapterFactory.getContainmentLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x22adea8877525e03L, 0x22adea88775261f2L, "column")), MetaAdapterFactory.getProperty(0x7eba6a284cc247b9L, 0xa392284573f2054aL, 0x43b3173822924fd2L, 0x22adea8877032f20L, "columnName")) + end;
  }
  public static boolean ifMacro_Condition_1_0(final IfMacroContext _context) {
    return (boolean) MAPlot__BehaviorDescriptor.hasXRange_id3AJ457wICpJ.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_1_1(final IfMacroContext _context) {
    return (boolean) MAPlot__BehaviorDescriptor.hasYRange_id4FCgsrOAthb.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_1_2(final IfMacroContext _context) {
    return (boolean) MAPlot__BehaviorDescriptor.hasTitle_id4FCgsrOB8t_.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_6_0(final IfMacroContext _context) {
    //  if there is no column with group ID, tranpose the table 
    return Table__BehaviorDescriptor.findColumnsWithGroup_id5hNeoNXWkF.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae347d9fL, "statsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")), MetaAdapterFactory.getContainmentLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd605ac5L, 0x39d2cd96c5e85fcbL, "myOwnTable")), "ID") != null;
  }
  public static boolean ifMacro_Condition_6_1(final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae347fdeL, "checkDuplicates")) == false;
  }
  public static boolean ifMacro_Condition_7_0(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0xc2b9f44459b7911L, 0x26f5565b738cca52L, "color")) != null);
  }
  public static SNode sourceNodeQuery_5_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x13016f4f44a76937L, 0x740e7fed5746b37L, "expression"));
  }
  public static Iterable<SNode> sourceNodesQuery_2_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x13016f4f44936489L, 0x51f1c789d32d78cL, "sets"));
  }
  public static Iterable<SNode> sourceNodesQuery_2_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x13016f4f44936489L, 0x51f1c789d32d78cL, "sets"));
  }
  public static Object varMacro_Value_1_0(final TemplateVarContext _context) {
    return (String) ISaveRVariableInSession__BehaviorDescriptor.getVariableName_id52J4nYvd$7N.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x34ed91dae4a675bcL, "statsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")));
  }
  public static Object varMacro_Value_1_1(final TemplateVarContext _context) {
    return "\"" + SPropertyOperations.getString(Sequence.fromIterable(ColumnLabel__BehaviorDescriptor.getColumnsWithGroup_id4WAdMLdBOXH.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x39af1051e0a6b9c6L, "geneName")), SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x34ed91dae4a675b5L, 0x34ed91dae4a675bcL, "statsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd605ac5L, 0x2f3745fadd605affL, "table")))).first(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "\"";
  }
  public static Object varMacro_Value_6_0(final TemplateVarContext _context) {
    return (String) ISaveRVariableInSession__BehaviorDescriptor.getVariableName_id52J4nYvd$7N.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe6c108c300094034L, 0xb684c506814ba197L, 0x4b25f265ae347d9cL, 0x4b25f265ae347d9fL, "statsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")));
  }
  private final Map<String, SourceNodeQuery> snqMethods = new HashMap<String, SourceNodeQuery>();
  {
    int i = 0;
    snqMethods.put("1369498147943238588", new QueriesGenerated.SNQ(i++));
  }
  @NotNull
  @Override
  public SourceNodeQuery getSourceNodeQuery(@NotNull QueryKey identity) {
    final String id = ((QueryKeyImpl) identity).getQueryNodeId().toString();
    if (!(snqMethods.containsKey(id))) {
      return super.getSourceNodeQuery(identity);
    }
    return snqMethods.get(id);
  }
  private static class SNQ implements SourceNodeQuery {
    private final int methodKey;
    public SNQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public SNode evaluate(@NotNull SourceSubstituteMacroNodeContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.sourceNodeQuery_5_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("1369498147942293934", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("1369498147943446902", new QueriesGenerated.SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    final String id = ((QueryKeyImpl) identity).getQueryNodeId().toString();
    if (!(snsqMethods.containsKey(id))) {
      return super.getSourceNodesQuery(identity);
    }
    return snsqMethods.get(id);
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_2_0(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_2_1(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("3813864828777740261", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "plot_id"));
    pvqMethods.put("4156558924934729999", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "tname"));
    pvqMethods.put("1369498147943192753", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "ID"));
    pvqMethods.put("95082356237865257", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "HGNC_symbol_from_feature"));
    pvqMethods.put("95082356238797284", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "adj.P.Val"));
    pvqMethods.put("1369498147942586032", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52bbL, 0x11106e60089e7685L, "value"), "0.20"));
    pvqMethods.put("95082356238792350", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "adj.P.Val"));
    pvqMethods.put("1369498147942554646", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "0.20"));
    pvqMethods.put("95082356238795961", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "AveExpr"));
    pvqMethods.put("1369498147942554667", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "0.0"));
    pvqMethods.put("95082356238734399", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "genes"));
    pvqMethods.put("95082356239103270", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "AveExpr"));
    pvqMethods.put("95082356238799047", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "logFC"));
    pvqMethods.put("95082356239155872", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "ID"));
    pvqMethods.put("95082356239168183", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "ID"));
    pvqMethods.put("95082356239167597", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "ID"));
    pvqMethods.put("4156558924934975380", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "xmin"));
    pvqMethods.put("4156558924935003489", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "xmax"));
    pvqMethods.put("4156558924935005514", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "ymin"));
    pvqMethods.put("4156558924935005523", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "ymax"));
    pvqMethods.put("4156558924935019670", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "title"));
    pvqMethods.put("3813864828777723410", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "aveexpr_threshold"));
    pvqMethods.put("3813864828777724424", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "aveexpr_threshold"));
    pvqMethods.put("8774426880322488602", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "genes"));
    pvqMethods.put("95082356240821671", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "genes"));
    pvqMethods.put("95082356238800909", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "AveExpr"));
    pvqMethods.put("95082356238801320", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "logFC"));
    pvqMethods.put("95082356241011088", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52bbL, 0x11106e60089e7685L, "value"), "0.5"));
    pvqMethods.put("95082356228016627", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f4627L, "pngPath"), ".png"));
    pvqMethods.put("95082356228016640", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f40f0L, "plotId"), "111"));
    pvqMethods.put("95082356228016649", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044bcL, "width"), "200"));
    pvqMethods.put("95082356228016658", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044c0L, "height"), "200"));
    pvqMethods.put("95082356228016667", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44b83dc3L, "statementId"), "11"));
    pvqMethods.put("1369498147941783149", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "plot_id"));
    pvqMethods.put("1369498147942298036", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "List1"));
    pvqMethods.put("1369498147942293665", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "id"));
    pvqMethods.put("1369498147943448068", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "name3"));
    pvqMethods.put("1369498147943450239", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "f"));
    pvqMethods.put("1369498147941774769", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f4627L, "pngPath"), ".png"));
    pvqMethods.put("1369498147941781048", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f40f0L, "plotId"), "111"));
    pvqMethods.put("1369498147941811140", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044bcL, "width"), "200"));
    pvqMethods.put("1369498147941815662", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044c0L, "height"), "200"));
    pvqMethods.put("1369498147943379688", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44b83dc3L, "statementId"), "11"));
    pvqMethods.put("1369498147942304836", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "id"));
    pvqMethods.put("7078032083058380500", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "calculateTSNE"));
    pvqMethods.put("876969668024768101", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "element-id"));
    pvqMethods.put("7950696009688764371", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52baL, 0x11106e60089e7566L, "value"), "1212"));
    pvqMethods.put("2397611765963429360", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52bbL, 0x11106e60089e7685L, "value"), "0.5"));
    pvqMethods.put("2397611765963458726", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52baL, 0x11106e60089e7566L, "value"), "1000"));
    pvqMethods.put("5022686753809035805", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52bbL, 0x11106e60089e7685L, "value"), "50"));
    pvqMethods.put("7950696009688726150", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52baL, 0x11106e60089e7566L, "value"), "1212"));
    pvqMethods.put("7950696009688424366", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52baL, 0x11106e60089e7566L, "value"), "2"));
    pvqMethods.put("2380808822333424878", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "INPUT"));
    pvqMethods.put("5415000645511222682", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "plot_id"));
    pvqMethods.put("7078032083058329575", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "input"));
    pvqMethods.put("2397611765964100823", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f4488ace3L, 0x6f4015e2c9ecbde8L, "tableName"), "tsne"));
    pvqMethods.put("2397611765964132910", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f4488ace3L, 0x157f2d8812f7de15L, "tableId"), "111"));
    pvqMethods.put("5415000645511223263", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f4627L, "pngPath"), ".png"));
    pvqMethods.put("5415000645511223276", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f40f0L, "plotId"), "111"));
    pvqMethods.put("5415000645511223285", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044bcL, "width"), "200"));
    pvqMethods.put("5415000645511223294", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044c0L, "height"), "200"));
    pvqMethods.put("5415000645511223303", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44b83dc3L, "statementId"), "11"));
    pvqMethods.put("7950696009688373038", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Output"));
    pvqMethods.put("3649379174726987476", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448adddbL, 0x7c7b9355b28afec0L, "nodeId"), "id"));
    pvqMethods.put("3649379174727165644", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448adddbL, 0x260d91b381fb25b7L, "enabled"), "true"));
    pvqMethods.put("876969668028228417", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "plot_id"));
    pvqMethods.put("876969668028133679", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "input"));
    pvqMethods.put("6556573545017898626", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "color"));
    pvqMethods.put("6556573545018077844", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b8L, 0x11106e60089e754eL, "value"), "color"));
    pvqMethods.put("876969668028148060", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "TSNE1"));
    pvqMethods.put("876969668028159545", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "TSNE2"));
    pvqMethods.put("6556573545017966542", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "cluster"));
    pvqMethods.put("876969668028228490", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f4627L, "pngPath"), ".png"));
    pvqMethods.put("876969668028228503", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f40f0L, "plotId"), "111"));
    pvqMethods.put("876969668028228512", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044bcL, "width"), "200"));
    pvqMethods.put("876969668028228521", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044c0L, "height"), "200"));
    pvqMethods.put("876969668028228530", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44b83dc3L, "statementId"), "11"));
    pvqMethods.put("876969668028228556", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448adddbL, 0x7c7b9355b28afec0L, "nodeId"), "id"));
    pvqMethods.put("876969668028228563", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f448adddbL, 0x260d91b381fb25b7L, "enabled"), "true"));
    pvqMethods.put("2498911240103488647", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "name"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(pvqMethods.containsKey(id))) {
      return super.getPropertyValueQuery(identity);
    }
    return pvqMethods.get(id);
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetValue_1_0(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetValue_1_1(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetValue_1_2(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetValue_1_3(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetValue_1_4(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetValue_1_5(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetValue_1_6(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetValue_1_7(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetValue_1_8(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetValue_1_9(ctx);
        case 10:
          return QueriesGenerated.propertyMacro_GetValue_1_10(ctx);
        case 11:
          return QueriesGenerated.propertyMacro_GetValue_1_11(ctx);
        case 12:
          return QueriesGenerated.propertyMacro_GetValue_1_12(ctx);
        case 13:
          return QueriesGenerated.propertyMacro_GetValue_1_13(ctx);
        case 14:
          return QueriesGenerated.propertyMacro_GetValue_1_14(ctx);
        case 15:
          return QueriesGenerated.propertyMacro_GetValue_1_15(ctx);
        case 16:
          return QueriesGenerated.propertyMacro_GetValue_1_16(ctx);
        case 17:
          return QueriesGenerated.propertyMacro_GetValue_1_17(ctx);
        case 18:
          return QueriesGenerated.propertyMacro_GetValue_1_18(ctx);
        case 19:
          return QueriesGenerated.propertyMacro_GetValue_1_19(ctx);
        case 20:
          return QueriesGenerated.propertyMacro_GetValue_1_20(ctx);
        case 21:
          return QueriesGenerated.propertyMacro_GetValue_1_21(ctx);
        case 22:
          return QueriesGenerated.propertyMacro_GetValue_1_22(ctx);
        case 23:
          return QueriesGenerated.propertyMacro_GetValue_1_23(ctx);
        case 24:
          return QueriesGenerated.propertyMacro_GetValue_1_24(ctx);
        case 25:
          return QueriesGenerated.propertyMacro_GetValue_1_25(ctx);
        case 26:
          return QueriesGenerated.propertyMacro_GetValue_1_26(ctx);
        case 27:
          return QueriesGenerated.propertyMacro_GetValue_1_27(ctx);
        case 28:
          return QueriesGenerated.propertyMacro_GetValue_1_28(ctx);
        case 29:
          return QueriesGenerated.propertyMacro_GetValue_1_29(ctx);
        case 30:
          return QueriesGenerated.propertyMacro_GetValue_1_30(ctx);
        case 31:
          return QueriesGenerated.propertyMacro_GetValue_1_31(ctx);
        case 32:
          return QueriesGenerated.propertyMacro_GetValue_1_32(ctx);
        case 33:
          return QueriesGenerated.propertyMacro_GetValue_2_0(ctx);
        case 34:
          return QueriesGenerated.propertyMacro_GetValue_2_1(ctx);
        case 35:
          return QueriesGenerated.propertyMacro_GetValue_2_2(ctx);
        case 36:
          return QueriesGenerated.propertyMacro_GetValue_2_3(ctx);
        case 37:
          return QueriesGenerated.propertyMacro_GetValue_2_4(ctx);
        case 38:
          return QueriesGenerated.propertyMacro_GetValue_2_5(ctx);
        case 39:
          return QueriesGenerated.propertyMacro_GetValue_2_6(ctx);
        case 40:
          return QueriesGenerated.propertyMacro_GetValue_2_7(ctx);
        case 41:
          return QueriesGenerated.propertyMacro_GetValue_2_8(ctx);
        case 42:
          return QueriesGenerated.propertyMacro_GetValue_2_9(ctx);
        case 43:
          return QueriesGenerated.propertyMacro_GetValue_4_0(ctx);
        case 44:
          return QueriesGenerated.propertyMacro_GetValue_6_0(ctx);
        case 45:
          return QueriesGenerated.propertyMacro_GetValue_6_1(ctx);
        case 46:
          return QueriesGenerated.propertyMacro_GetValue_6_2(ctx);
        case 47:
          return QueriesGenerated.propertyMacro_GetValue_6_3(ctx);
        case 48:
          return QueriesGenerated.propertyMacro_GetValue_6_4(ctx);
        case 49:
          return QueriesGenerated.propertyMacro_GetValue_6_5(ctx);
        case 50:
          return QueriesGenerated.propertyMacro_GetValue_6_6(ctx);
        case 51:
          return QueriesGenerated.propertyMacro_GetValue_6_7(ctx);
        case 52:
          return QueriesGenerated.propertyMacro_GetValue_6_8(ctx);
        case 53:
          return QueriesGenerated.propertyMacro_GetValue_6_9(ctx);
        case 54:
          return QueriesGenerated.propertyMacro_GetValue_6_10(ctx);
        case 55:
          return QueriesGenerated.propertyMacro_GetValue_6_11(ctx);
        case 56:
          return QueriesGenerated.propertyMacro_GetValue_6_12(ctx);
        case 57:
          return QueriesGenerated.propertyMacro_GetValue_6_13(ctx);
        case 58:
          return QueriesGenerated.propertyMacro_GetValue_6_14(ctx);
        case 59:
          return QueriesGenerated.propertyMacro_GetValue_6_15(ctx);
        case 60:
          return QueriesGenerated.propertyMacro_GetValue_6_16(ctx);
        case 61:
          return QueriesGenerated.propertyMacro_GetValue_6_17(ctx);
        case 62:
          return QueriesGenerated.propertyMacro_GetValue_6_18(ctx);
        case 63:
          return QueriesGenerated.propertyMacro_GetValue_6_19(ctx);
        case 64:
          return QueriesGenerated.propertyMacro_GetValue_6_20(ctx);
        case 65:
          return QueriesGenerated.propertyMacro_GetValue_7_0(ctx);
        case 66:
          return QueriesGenerated.propertyMacro_GetValue_7_1(ctx);
        case 67:
          return QueriesGenerated.propertyMacro_GetValue_7_2(ctx);
        case 68:
          return QueriesGenerated.propertyMacro_GetValue_7_3(ctx);
        case 69:
          return QueriesGenerated.propertyMacro_GetValue_7_4(ctx);
        case 70:
          return QueriesGenerated.propertyMacro_GetValue_7_5(ctx);
        case 71:
          return QueriesGenerated.propertyMacro_GetValue_7_6(ctx);
        case 72:
          return QueriesGenerated.propertyMacro_GetValue_7_7(ctx);
        case 73:
          return QueriesGenerated.propertyMacro_GetValue_7_8(ctx);
        case 74:
          return QueriesGenerated.propertyMacro_GetValue_7_9(ctx);
        case 75:
          return QueriesGenerated.propertyMacro_GetValue_7_10(ctx);
        case 76:
          return QueriesGenerated.propertyMacro_GetValue_7_11(ctx);
        case 77:
          return QueriesGenerated.propertyMacro_GetValue_7_12(ctx);
        case 78:
          return QueriesGenerated.propertyMacro_GetValue_7_13(ctx);
        case 79:
          return QueriesGenerated.propertyMacro_GetValue_8_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, IfMacroCondition> imcMethods = new HashMap<String, IfMacroCondition>();
  {
    int i = 0;
    imcMethods.put("4156558924934965682", new QueriesGenerated.IfMC(i++));
    imcMethods.put("4156558924935005531", new QueriesGenerated.IfMC(i++));
    imcMethods.put("4156558924935016988", new QueriesGenerated.IfMC(i++));
    imcMethods.put("876969668024560380", new QueriesGenerated.IfMC(i++));
    imcMethods.put("2397611765963449426", new QueriesGenerated.IfMC(i++));
    imcMethods.put("6556573545017823158", new QueriesGenerated.IfMC(i++));
  }
  @NotNull
  @Override
  public IfMacroCondition getIfMacroCondition(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(imcMethods.containsKey(id))) {
      return super.getIfMacroCondition(identity);
    }
    return imcMethods.get(id);
  }
  private static class IfMC implements IfMacroCondition {
    private final int methodKey;
    public IfMC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(@NotNull IfMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.ifMacro_Condition_1_0(ctx);
        case 1:
          return QueriesGenerated.ifMacro_Condition_1_1(ctx);
        case 2:
          return QueriesGenerated.ifMacro_Condition_1_2(ctx);
        case 3:
          return QueriesGenerated.ifMacro_Condition_6_0(ctx);
        case 4:
          return QueriesGenerated.ifMacro_Condition_6_1(ctx);
        case 5:
          return QueriesGenerated.ifMacro_Condition_7_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for if macro %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, VariableValueQuery> vvqMethods = new HashMap<String, VariableValueQuery>();
  {
    vvqMethods.put("6256772833737875", new QueriesGenerated.VVQ(0));
    vvqMethods.put("6256772833737878", new QueriesGenerated.VVQ(1));
    vvqMethods.put("6256772833737880", new QueriesGenerated.VVQ(2));
  }
  @NotNull
  @Override
  public VariableValueQuery getVariableValueQuery(@NotNull QueryKey queryKey) {
    final String id = queryKey.getTemplateNode().getNodeId().toString();
    if (!(vvqMethods.containsKey(id))) {
      return super.getVariableValueQuery(queryKey);
    }
    return vvqMethods.get(id);
  }
  private static class VVQ implements VariableValueQuery {
    private final int methodKey;
    /*package*/ VVQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull TemplateVarContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.varMacro_Value_1_0(ctx);
        case 1:
          return QueriesGenerated.varMacro_Value_1_1(ctx);
        case 2:
          return QueriesGenerated.varMacro_Value_6_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
}
