package org.campagnelab.metar.scnorm.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import org.campagnelab.metar.tables.behavior.ISaveRVariableInSession__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import org.campagnelab.metar.tables.behavior.Table__BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.AttributeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import jetbrains.mps.internal.collections.runtime.IterableUtils;
import jetbrains.mps.internal.collections.runtime.ISelector;
import org.campagnelab.metar.tables.behavior.ColumnGroup__BehaviorDescriptor;
import org.campagnelab.metar.code.generator.helpers.RPath;
import org.campagnelab.metar.scnorm.behavior.CheckCountDepth__BehaviorDescriptor;
import org.campagnelab.metar.scnorm.behavior.ScanKOption__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.campagnelab.instantrefresh.behavior.IAtomic__BehaviorDescriptor;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_480556465136580368(final PropertyMacroContext _context) {
    return (String) ISaveRVariableInSession__BehaviorDescriptor.getVariableName_id52J4nYvd$7N.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae15e5b77L, 0x5f510ae1257b01L, "countsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")));
  }
  public static Object propertyMacro_GetPropertyValue_480556465136580384(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_480556465136580422(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(Sequence.fromIterable(Table__BehaviorDescriptor.findColumnsWithGroup_id5hNeoNXWkF.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae15e5b77L, 0x5f510ae1257b01L, "countsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd605ac5L, 0x2f3745fadd605affL, "table")), "ID")).first(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_8544263073411224539(final PropertyMacroContext _context) {
    Iterable<SNode> columns = ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae15e5b77L, 0x5f510ae1257b01L, "countsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd605ac5L, 0x2f3745fadd605affL, "table")), MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a74L, "columns"))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return ListSequence.fromList(SLinkOperations.getChildren(AttributeOperations.getAttribute(it, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745faddba8bacL, "org.campagnelab.metar.tables.structure.ColumnAnnotation"))), MetaAdapterFactory.getContainmentLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745faddba8bacL, 0x2f3745faddba9108L, "groups"))).any(new IWhereFilter<SNode>() {
          public boolean accept(SNode it) {
            return eq_x583g4_a0a0a0a0a0a0a0a0a0a0a3(SPropertyOperations.getString(SLinkOperations.getTarget(it, MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745faddba8c07L, 0x2f3745faddba8c08L, "columnGroup")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")), "counts");
          }
        });
      }
    });
    return "\"" + IterableUtils.join(Sequence.fromIterable(columns).select(new ISelector<SNode, String>() {
      public String select(SNode column) {
        SNode cGroup = Sequence.fromIterable(SLinkOperations.collect(SLinkOperations.getChildren(AttributeOperations.getAttribute(column, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745faddba8bacL, "org.campagnelab.metar.tables.structure.ColumnAnnotation"))), MetaAdapterFactory.getContainmentLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745faddba8bacL, 0x2f3745faddba9108L, "groups")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745faddba8c07L, 0x2f3745faddba8c08L, "columnGroup"))).findFirst(new IWhereFilter<SNode>() {
          public boolean accept(SNode cGroup) {
            return Sequence.fromIterable(ColumnGroup__BehaviorDescriptor.uses_id6XP3gVdXeLZ.invoke(cGroup)).contains(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae1257b00L, 0x4778ac6ee8f93e27L, "condition")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x6f750d0ecde3e9dfL, 0x6f750d0ecde3e9e0L, "usage")));
          }
        });
        return SPropertyOperations.getString(cGroup, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
    }), "\",\"") + "\"";
  }
  public static Object propertyMacro_GetPropertyValue_480556465136588096(final PropertyMacroContext _context) {
    return new RPath(CheckCountDepth__BehaviorDescriptor.getOutputPath_idqFhSWmYbmX.invoke(_context.getNode()) + ScanKOption__BehaviorDescriptor.kPrefix_id5X5p3g3lvmI.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae1257b00L, 0x5f4564340350eaa6L, "scanK"))) + "_").toString();
  }
  public static Object propertyMacro_GetPropertyValue_480556465136821726(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae15e5b77L, 0x5f510ae15ebb66L, "filterCellProportion"));
  }
  public static Object propertyMacro_GetPropertyValue_6865003381553004105(final PropertyMacroContext _context) {
    {
      final SNode fixed = SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae1257b00L, 0x5f4564340350eaa6L, "scanK"));
      if (SNodeOperations.isInstanceOf(fixed, MetaAdapterFactory.getConcept(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f4564340350eaadL, "org.campagnelab.metar.scnorm.structure.FixedK"))) {
        return Integer.toString(SPropertyOperations.getInteger(fixed, MetaAdapterFactory.getProperty(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f4564340350eaadL, 0x5f4564340350eaaeL, "K")));
      }
    }
    return "-1";
  }
  public static Object propertyMacro_GetPropertyValue_480556465136761024(final PropertyMacroContext _context) {
    return (String) ISaveRVariableInSession__BehaviorDescriptor.getVariableName_id52J4nYvd$7N.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae1257b00L, 0x5f510ae1257b13L, "normalizedTable")));
  }
  public static Object propertyMacro_GetPropertyValue_49418204378381487(final PropertyMacroContext _context) {
    return (String) ISaveRVariableInSession__BehaviorDescriptor.getVariableName_id52J4nYvd$7N.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae1257b00L, 0x5f510ae1257b13L, "normalizedTable")));
  }
  public static Object propertyMacro_GetPropertyValue_49418204378384448(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(Sequence.fromIterable(Table__BehaviorDescriptor.findColumnsWithGroup_id5hNeoNXWkF.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae15e5b77L, 0x5f510ae1257b01L, "countsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd605ac5L, 0x2f3745fadd605affL, "table")), "ID")).first(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_49418204378647515(final PropertyMacroContext _context) {
    return (String) ISaveRVariableInSession__BehaviorDescriptor.getVariableName_id52J4nYvd$7N.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae15e5b77L, 0x5f510ae1257b01L, "countsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")));
  }
  public static Object propertyMacro_GetPropertyValue_49418204378641616(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(Sequence.fromIterable(Table__BehaviorDescriptor.findColumnsWithGroup_id5hNeoNXWkF.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae15e5b77L, 0x5f510ae1257b01L, "countsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd605ac5L, 0x2f3745fadd605affL, "table")), "ID")).first(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_480556465136580475(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetPropertyValue_480556465136580482(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetPropertyValue_480556465135944284(final PropertyMacroContext _context) {
    return (String) ISaveRVariableInSession__BehaviorDescriptor.getVariableName_id52J4nYvd$7N.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae15e5b77L, 0x5f510ae1257b01L, "countsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")));
  }
  public static Object propertyMacro_GetPropertyValue_8544263073412629227(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_480556465135997729(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(Sequence.fromIterable(Table__BehaviorDescriptor.findColumnsWithGroup_id5hNeoNXWkF.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae15e5b77L, 0x5f510ae1257b01L, "countsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd605ac5L, 0x2f3745fadd605affL, "table")), "ID")).first(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_26829229960117245(final PropertyMacroContext _context) {
    return new RPath(CheckCountDepth__BehaviorDescriptor.getOutputPath_idqFhSWmYbmX.invoke(_context.getNode())).toString();
  }
  public static Object propertyMacro_GetPropertyValue_480556465136151482(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae15e5b77L, 0x5f510ae15ebb66L, "filterCellProportion"));
  }
  public static Object propertyMacro_GetPropertyValue_1369498147940466311(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetPropertyValue_480556465136101175(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_6865003381553089603(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae1257b00L, 0x5f4564340350eaa6L, "scanK")), MetaAdapterFactory.getConcept(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f4564340350eaadL, "org.campagnelab.metar.scnorm.structure.FixedK"));
  }
  public static Iterable<SNode> sourceNodesQuery_8544263073411795770(final SourceSubstituteMacroNodesContext _context) {
    //  remove columns that do not contain counts: 
    return ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae15e5b77L, 0x5f510ae1257b01L, "countsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd605ac5L, 0x2f3745fadd605affL, "table")), MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a74L, "columns"))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return Sequence.fromIterable(SLinkOperations.collect(SLinkOperations.getChildren(AttributeOperations.getAttribute(it, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745faddba8bacL, "org.campagnelab.metar.tables.structure.ColumnAnnotation"))), MetaAdapterFactory.getContainmentLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745faddba8bacL, 0x2f3745faddba9108L, "groups")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745faddba8c07L, 0x2f3745faddba8c08L, "columnGroup"))).all(new IWhereFilter<SNode>() {
          public boolean accept(SNode cGroup) {
            return neq_x583g4_a0a0a0a0a0a0a0a0a0b0w(SPropertyOperations.getString(cGroup, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")), "counts");
          }
        });
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_8544263073412629253(final SourceSubstituteMacroNodesContext _context) {
    //  remove columns that do not contain counts: 
    return ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xac875888d38140acL, 0x8fad78c941372a9eL, 0x5f510ae15e5b77L, 0x5f510ae1257b01L, "countsTable")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd5e5fb7L, 0x2f3745fadd5e82e5L, "table")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd605ac5L, 0x2f3745fadd605affL, "table")), MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a74L, "columns"))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return Sequence.fromIterable(SLinkOperations.collect(SLinkOperations.getChildren(AttributeOperations.getAttribute(it, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745faddba8bacL, "org.campagnelab.metar.tables.structure.ColumnAnnotation"))), MetaAdapterFactory.getContainmentLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745faddba8bacL, 0x2f3745faddba9108L, "groups")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745faddba8c07L, 0x2f3745faddba8c08L, "columnGroup"))).all(new IWhereFilter<SNode>() {
          public boolean accept(SNode cGroup) {
            return neq_x583g4_a0a0a0a0a0a0a0a0a0b0x(SPropertyOperations.getString(cGroup, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")), "counts");
          }
        });
      }
    });
  }
  private static boolean eq_x583g4_a0a0a0a0a0a0a0a0a0a0a3(Object a, Object b) {
    return (a != null ? a.equals(b) : a == b);
  }
  private static boolean neq_x583g4_a0a0a0a0a0a0a0a0a0b0w(Object a, Object b) {
    return !(((a != null ? a.equals(b) : a == b)));
  }
  private static boolean neq_x583g4_a0a0a0a0a0a0a0a0a0b0x(Object a, Object b) {
    return !(((a != null ? a.equals(b) : a == b)));
  }
}
