package org.campagnelab.metar.r.metar.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import org.campagnelab.instantrefresh.behavior.IAtomic__BehaviorDescriptor;
import org.campagnelab.metar.tables.behavior.Plot__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_213294746055999216(final PropertyMacroContext _context) {
    return "plot_" + IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetPropertyValue_1369498147941731525(final PropertyMacroContext _context) {
    return (String) Plot__BehaviorDescriptor.getPath_id6X05ubabEHv.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe4bb94f91202448eL, 0x98f6d108577add14L, 0x2f5c67102d33820L, 0x2f5c67102d33821L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_1369498147941795250(final PropertyMacroContext _context) {
    return Integer.toString((int) Plot__BehaviorDescriptor.getWidth_id32mm940cTd2.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe4bb94f91202448eL, 0x98f6d108577add14L, 0x2f5c67102d33820L, 0x2f5c67102d33821L, "plot"))));
  }
  public static Object propertyMacro_GetPropertyValue_1369498147941799268(final PropertyMacroContext _context) {
    return Integer.toString((int) Plot__BehaviorDescriptor.getHeight_id32mm940d1rP.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe4bb94f91202448eL, 0x98f6d108577add14L, 0x2f5c67102d33820L, 0x2f5c67102d33821L, "plot"))));
  }
  public static Object propertyMacro_GetPropertyValue_1369498147941730058(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(_context.getNode());
  }
  public static SNode sourceNodeQuery_213294746052014905(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe4bb94f91202448eL, 0x98f6d108577add14L, 0x2f5c67102d33820L, 0x2f5c67102d33828L, "expression"));
  }
}
