package org.campagnelab.modeling.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.PropertyMacroContext;
import org.campagnelab.metar.tables.behavior.Plot__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.campagnelab.metar.tables.behavior.TableRef__BehaviorDescriptor;
import org.campagnelab.metar.tables.behavior.ColumnRef__BehaviorDescriptor;
import org.campagnelab.metar.code.generator.helpers.RPath;
import org.campagnelab.instantrefresh.behavior.IAtomic__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.campagnelab.metar.code.generator.helpers.NameHelper;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.campagnelab.metar.tables.behavior.PlotBuilderStatement__BehaviorDescriptor;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.TemplateVarContext;
import java.util.Map;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.generator.impl.query.IfMacroCondition;
import jetbrains.mps.generator.impl.query.VariableValueQuery;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static Object propertyMacro_GetPropertyValue_5128164036542412338(final PropertyMacroContext _context) {
    return "plot_" + Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x5347fb6bb3853ab4L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_3208973838627305928(final PropertyMacroContext _context) {
    return (String) TableRef__BehaviorDescriptor.getVariableName_id7tPuoi15D0G.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x3dc59a0f37ff74c7L, "table")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819406507(final PropertyMacroContext _context) {
    return (String) ColumnRef__BehaviorDescriptor.getCleanColumnName_id2rPl_HNk7G7.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x472ae605640b2784L, "progressColumn")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819406738(final PropertyMacroContext _context) {
    return (String) ColumnRef__BehaviorDescriptor.getCleanColumnName_id2rPl_HNk7G7.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x472ae605640b2789L, "performanceColumn")));
  }
  public static Object propertyMacro_GetPropertyValue_5128164036542431290(final PropertyMacroContext _context) {
    return new RPath(Plot__BehaviorDescriptor.getPath_id6X05ubabEHv.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x5347fb6bb3853ab4L, "plot")))).toString();
  }
  public static Object propertyMacro_GetPropertyValue_5128164036542431301(final PropertyMacroContext _context) {
    return (String) Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x5347fb6bb3853ab4L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_5128164036542431307(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getWidth_id32mm940cTd2.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x5347fb6bb3853ab4L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_5128164036542431316(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getHeight_id32mm940d1rP.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x5347fb6bb3853ab4L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_5128164036542431325(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x7c5f892f445924a8L, "org.campagnelab.metar.tables.structure.Statement")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819441562(final PropertyMacroContext _context) {
    return "plot_" + Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670086L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819426073(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670085L, "table")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x3dc59a0f37f897b3L, 0x3dc59a0f37f89c07L, "table")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819434964(final PropertyMacroContext _context) {
    return (String) ColumnRef__BehaviorDescriptor.getCleanColumnName_id2rPl_HNk7G7.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670087L, "predictedProbability")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819439249(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670085L, "table")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x3dc59a0f37f897b3L, 0x3dc59a0f37f89c07L, "table")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819438206(final PropertyMacroContext _context) {
    return (String) ColumnRef__BehaviorDescriptor.getCleanColumnName_id2rPl_HNk7G7.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670088L, "trueLabel")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819486428(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a567e68eL, "showGuides")) ? "TRUE" : "FALSE");
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819489751(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a567e68cL, "numberOfBootstrapSamples")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819457371(final PropertyMacroContext _context) {
    return new RPath(Plot__BehaviorDescriptor.getPath_id6X05ubabEHv.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670086L, "plot")))).toString();
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819457384(final PropertyMacroContext _context) {
    return (String) Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670086L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819457393(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getWidth_id32mm940cTd2.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670086L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819457402(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getHeight_id32mm940d1rP.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670086L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819457411(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x7c5f892f445924a8L, "org.campagnelab.metar.tables.structure.Statement")));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796896423(final PropertyMacroContext _context) {
    return "plot_" + Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(PlotBuilderStatement__BehaviorDescriptor.getPlot_idL2v$scW7kG.invoke(_context.getNode()));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796898111(final PropertyMacroContext _context) {
    return ((String) _context.getVariable("var:tableName"));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796913898(final PropertyMacroContext _context) {
    return (String) ColumnRef__BehaviorDescriptor.getCleanColumnName_id2rPl_HNk7G7.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x7775798481158907L, 0x777579848115890aL, "predictedProbability")));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796917595(final PropertyMacroContext _context) {
    return ((String) _context.getVariable("var:tableName"));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796916396(final PropertyMacroContext _context) {
    return (String) ColumnRef__BehaviorDescriptor.getCleanColumnName_id2rPl_HNk7G7.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x7775798481158907L, 0x777579848115890bL, "trueLabel")));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796890663(final PropertyMacroContext _context) {
    return new RPath(Plot__BehaviorDescriptor.getPath_id6X05ubabEHv.invoke(PlotBuilderStatement__BehaviorDescriptor.getPlot_idL2v$scW7kG.invoke(_context.getNode()))).toString();
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796890676(final PropertyMacroContext _context) {
    return (String) Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(PlotBuilderStatement__BehaviorDescriptor.getPlot_idL2v$scW7kG.invoke(_context.getNode()));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796890685(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getWidth_id32mm940cTd2.invoke(PlotBuilderStatement__BehaviorDescriptor.getPlot_idL2v$scW7kG.invoke(_context.getNode()));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796890694(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getHeight_id32mm940d1rP.invoke(PlotBuilderStatement__BehaviorDescriptor.getPlot_idL2v$scW7kG.invoke(_context.getNode()));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796890703(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x7c5f892f445924a8L, "org.campagnelab.metar.tables.structure.Statement")));
  }
  public static boolean ifMacro_Condition_3260011451819406978(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x472ae605640b2780L, "by")) != null);
  }
  public static Object insertMacro_varValue_8607919872796911435(final TemplateVarContext _context) {
    return (String) TableRef__BehaviorDescriptor.getVariableName_id7tPuoi15D0G.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x7775798481158907L, 0x7775798481158908L, "table")));
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("5128164036542412337", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "plotId"));
    pvqMethods.put("3208973838627305927", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "x"));
    pvqMethods.put("3260011451819406506", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "epoch"));
    pvqMethods.put("3260011451819406737", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "AUC"));
    pvqMethods.put("5128164036542431289", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f4627L, "pngPath"), ".png"));
    pvqMethods.put("5128164036542431300", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f40f0L, "plotId"), "111"));
    pvqMethods.put("5128164036542431306", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044bcL, "width"), "200"));
    pvqMethods.put("5128164036542431315", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044c0L, "height"), "200"));
    pvqMethods.put("5128164036542431324", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44b83dc3L, "statementId"), "11"));
    pvqMethods.put("3260011451819441561", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "plot"));
    pvqMethods.put("3260011451819426072", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "test"));
    pvqMethods.put("3260011451819434963", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "ProbabilityMut"));
    pvqMethods.put("3260011451819439248", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "test"));
    pvqMethods.put("3260011451819438205", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "mutatedLabel"));
    pvqMethods.put("3260011451819486427", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52baL, 0x11106e60089e7566L, "value"), "0"));
    pvqMethods.put("3260011451819489750", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52baL, 0x11106e60089e7566L, "value"), "0"));
    pvqMethods.put("3260011451819457370", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f4627L, "pngPath"), ".png"));
    pvqMethods.put("3260011451819457383", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f40f0L, "plotId"), "111"));
    pvqMethods.put("3260011451819457392", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044bcL, "width"), "200"));
    pvqMethods.put("3260011451819457401", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044c0L, "height"), "200"));
    pvqMethods.put("3260011451819457410", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44b83dc3L, "statementId"), "11"));
    pvqMethods.put("8607919872796896422", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "plot_id"));
    pvqMethods.put("8607919872796898110", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "training"));
    pvqMethods.put("8607919872796913897", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "ProbabilityMut"));
    pvqMethods.put("8607919872796917594", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "training"));
    pvqMethods.put("8607919872796916395", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "mutatedLabel"));
    pvqMethods.put("8607919872796890662", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f4627L, "pngPath"), ".png"));
    pvqMethods.put("8607919872796890675", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f449f40f0L, "plotId"), "111"));
    pvqMethods.put("8607919872796890684", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044bcL, "width"), "200"));
    pvqMethods.put("8607919872796890693", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44a044c0L, "height"), "200"));
    pvqMethods.put("8607919872796890702", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0x544eb3a5f68f41edL, 0x98e0db6291e897fbL, 0x13016f4f449f40efL, 0x13016f4f44b83dc3L, "statementId"), "11"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(pvqMethods.containsKey(id))) {
      return super.getPropertyValueQuery(identity);
    }
    return pvqMethods.get(id);
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetPropertyValue_5128164036542412338(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3208973838627305928(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819406507(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819406738(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetPropertyValue_5128164036542431290(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetPropertyValue_5128164036542431301(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetPropertyValue_5128164036542431307(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetPropertyValue_5128164036542431316(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetPropertyValue_5128164036542431325(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819441562(ctx);
        case 10:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819426073(ctx);
        case 11:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819434964(ctx);
        case 12:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819439249(ctx);
        case 13:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819438206(ctx);
        case 14:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819486428(ctx);
        case 15:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819489751(ctx);
        case 16:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819457371(ctx);
        case 17:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819457384(ctx);
        case 18:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819457393(ctx);
        case 19:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819457402(ctx);
        case 20:
          return QueriesGenerated.propertyMacro_GetPropertyValue_3260011451819457411(ctx);
        case 21:
          return QueriesGenerated.propertyMacro_GetPropertyValue_8607919872796896423(ctx);
        case 22:
          return QueriesGenerated.propertyMacro_GetPropertyValue_8607919872796898111(ctx);
        case 23:
          return QueriesGenerated.propertyMacro_GetPropertyValue_8607919872796913898(ctx);
        case 24:
          return QueriesGenerated.propertyMacro_GetPropertyValue_8607919872796917595(ctx);
        case 25:
          return QueriesGenerated.propertyMacro_GetPropertyValue_8607919872796916396(ctx);
        case 26:
          return QueriesGenerated.propertyMacro_GetPropertyValue_8607919872796890663(ctx);
        case 27:
          return QueriesGenerated.propertyMacro_GetPropertyValue_8607919872796890676(ctx);
        case 28:
          return QueriesGenerated.propertyMacro_GetPropertyValue_8607919872796890685(ctx);
        case 29:
          return QueriesGenerated.propertyMacro_GetPropertyValue_8607919872796890694(ctx);
        case 30:
          return QueriesGenerated.propertyMacro_GetPropertyValue_8607919872796890703(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, IfMacroCondition> imcMethods = new HashMap<String, IfMacroCondition>();
  {
    int i = 0;
    imcMethods.put("3260011451819406976", new QueriesGenerated.IfMC(i++));
  }
  @NotNull
  @Override
  public IfMacroCondition getIfMacroCondition(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(imcMethods.containsKey(id))) {
      return super.getIfMacroCondition(identity);
    }
    return imcMethods.get(id);
  }
  private static class IfMC implements IfMacroCondition {
    private final int methodKey;
    public IfMC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(@NotNull IfMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.ifMacro_Condition_3260011451819406978(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for if macro %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, VariableValueQuery> vvqMethods = new HashMap<String, VariableValueQuery>();
  {
    vvqMethods.put("8607919872796911433", new QueriesGenerated.VVQ(0));
  }
  @NotNull
  @Override
  public VariableValueQuery getVariableValueQuery(@NotNull QueryKey queryKey) {
    final String id = queryKey.getTemplateNode().getNodeId().toString();
    if (!(vvqMethods.containsKey(id))) {
      return super.getVariableValueQuery(queryKey);
    }
    return vvqMethods.get(id);
  }
  private static class VVQ implements VariableValueQuery {
    private final int methodKey;
    /*package*/ VVQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull TemplateVarContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.insertMacro_varValue_8607919872796911435(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
}
