package org.campagnelab.modeling.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import org.campagnelab.metar.tables.behavior.Plot__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.campagnelab.metar.tables.behavior.TableRef__BehaviorDescriptor;
import org.campagnelab.metar.tables.behavior.ColumnRef__BehaviorDescriptor;
import org.campagnelab.metar.code.generator.helpers.RPath;
import org.campagnelab.instantrefresh.behavior.IAtomic__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.campagnelab.metar.code.generator.helpers.NameHelper;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.campagnelab.metar.tables.behavior.PlotBuilderStatement__BehaviorDescriptor;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.TemplateVarContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_5128164036542412338(final PropertyMacroContext _context) {
    return "plot_" + Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x5347fb6bb3853ab4L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_3208973838627305928(final PropertyMacroContext _context) {
    return (String) TableRef__BehaviorDescriptor.getVariableName_id7tPuoi15D0G.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x3dc59a0f37ff74c7L, "table")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819406507(final PropertyMacroContext _context) {
    return (String) ColumnRef__BehaviorDescriptor.getCleanColumnName_id2rPl_HNk7G7.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x472ae605640b2784L, "progressColumn")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819406738(final PropertyMacroContext _context) {
    return (String) ColumnRef__BehaviorDescriptor.getCleanColumnName_id2rPl_HNk7G7.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x472ae605640b2789L, "performanceColumn")));
  }
  public static Object propertyMacro_GetPropertyValue_5128164036542431290(final PropertyMacroContext _context) {
    return new RPath(Plot__BehaviorDescriptor.getPath_id6X05ubabEHv.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x5347fb6bb3853ab4L, "plot")))).toString();
  }
  public static Object propertyMacro_GetPropertyValue_5128164036542431301(final PropertyMacroContext _context) {
    return (String) Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x5347fb6bb3853ab4L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_5128164036542431307(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getWidth_id32mm940cTd2.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x5347fb6bb3853ab4L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_5128164036542431316(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getHeight_id32mm940d1rP.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x5347fb6bb3853ab4L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_5128164036542431325(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x7c5f892f445924a8L, "org.campagnelab.metar.tables.structure.Statement")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819441562(final PropertyMacroContext _context) {
    return "plot_" + Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670086L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819426073(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670085L, "table")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x3dc59a0f37f897b3L, 0x3dc59a0f37f89c07L, "table")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819434964(final PropertyMacroContext _context) {
    return (String) ColumnRef__BehaviorDescriptor.getCleanColumnName_id2rPl_HNk7G7.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670087L, "predictedProbability")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819439249(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670085L, "table")), MetaAdapterFactory.getReferenceLink(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x3dc59a0f37f897b3L, 0x3dc59a0f37f89c07L, "table")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819438206(final PropertyMacroContext _context) {
    return (String) ColumnRef__BehaviorDescriptor.getCleanColumnName_id2rPl_HNk7G7.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670088L, "trueLabel")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819486428(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a567e68eL, "showGuides")) ? "TRUE" : "FALSE");
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819489751(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a567e68cL, "numberOfBootstrapSamples")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819457371(final PropertyMacroContext _context) {
    return new RPath(Plot__BehaviorDescriptor.getPath_id6X05ubabEHv.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670086L, "plot")))).toString();
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819457384(final PropertyMacroContext _context) {
    return (String) Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670086L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819457393(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getWidth_id32mm940cTd2.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670086L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819457402(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getHeight_id32mm940d1rP.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x2d3de324a567003eL, 0x2d3de324a5670086L, "plot")));
  }
  public static Object propertyMacro_GetPropertyValue_3260011451819457411(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x7c5f892f445924a8L, "org.campagnelab.metar.tables.structure.Statement")));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796896423(final PropertyMacroContext _context) {
    return "plot_" + Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(PlotBuilderStatement__BehaviorDescriptor.getPlot_idL2v$scW7kG.invoke(_context.getNode()));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796898111(final PropertyMacroContext _context) {
    return ((String) _context.getVariable("var:tableName"));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796913898(final PropertyMacroContext _context) {
    return (String) ColumnRef__BehaviorDescriptor.getCleanColumnName_id2rPl_HNk7G7.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x7775798481158907L, 0x777579848115890aL, "predictedProbability")));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796917595(final PropertyMacroContext _context) {
    return ((String) _context.getVariable("var:tableName"));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796916396(final PropertyMacroContext _context) {
    return (String) ColumnRef__BehaviorDescriptor.getCleanColumnName_id2rPl_HNk7G7.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x7775798481158907L, 0x777579848115890bL, "trueLabel")));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796890663(final PropertyMacroContext _context) {
    return new RPath(Plot__BehaviorDescriptor.getPath_id6X05ubabEHv.invoke(PlotBuilderStatement__BehaviorDescriptor.getPlot_idL2v$scW7kG.invoke(_context.getNode()))).toString();
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796890676(final PropertyMacroContext _context) {
    return (String) Plot__BehaviorDescriptor.getStatementId_id6WPhx9njIUt.invoke(PlotBuilderStatement__BehaviorDescriptor.getPlot_idL2v$scW7kG.invoke(_context.getNode()));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796890685(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getWidth_id32mm940cTd2.invoke(PlotBuilderStatement__BehaviorDescriptor.getPlot_idL2v$scW7kG.invoke(_context.getNode()));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796890694(final PropertyMacroContext _context) {
    return (int) Plot__BehaviorDescriptor.getHeight_id32mm940d1rP.invoke(PlotBuilderStatement__BehaviorDescriptor.getPlot_idL2v$scW7kG.invoke(_context.getNode()));
  }
  public static Object propertyMacro_GetPropertyValue_8607919872796890703(final PropertyMacroContext _context) {
    return (String) IAtomic__BehaviorDescriptor.id_idhlbLQwkRFj.invoke(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x7c5f892f445924a8L, "org.campagnelab.metar.tables.structure.Statement")));
  }
  public static boolean ifMacro_Condition_3260011451819406978(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x472ae605640b2744L, 0x472ae605640b2780L, "by")) != null);
  }
  public static Object insertMacro_varValue_8607919872796911435(final TemplateVarContext _context) {
    return (String) TableRef__BehaviorDescriptor.getVariableName_id7tPuoi15D0G.invoke(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe3c980773ecd4a0dL, 0xa28fc2f3e3cec764L, 0x7775798481158907L, 0x7775798481158908L, "table")));
  }
}
